/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaBrilhoEContraste.java
 *
 * Created on 01/08/2011, 17:56:47
 */
package processamentodeimagem1;

import com.pearsoneduc.ip.op.LinearOp;
import com.pearsoneduc.ip.op.ThresholdOp;
import java.util.Hashtable;
import java.util.Vector;
import javax.media.jai.PlanarImage;
import javax.swing.JScrollPane;

/**
 *
 * @author marcelo
 */
public class JanelaBrilhoEContraste extends javax.swing.JFrame implements JanelaBrilhoEContrasteSubject {

    private JanelaBrilhoEContrasteObserver principal;
    private PlanarImage srcImage;
    private ImageView imageview;
    private GreyMapPanel painelBrilhoEContrasteLogico;
    
    /** Creates new form JanelaBrilhoEContraste */
    public JanelaBrilhoEContraste(PlanarImage srcImage,JanelaBrilhoEContrasteObserver observador) {
        initComponents();
        this.srcImage = srcImage;
        LinearOp op = new LinearOp();
        imageview = new ImageView(srcImage.getAsBufferedImage(),op);
        
        Hashtable ops = new Hashtable();
            ops.put("Brilho", op);
            ops.put("Contraste", new ThresholdOp(128));

        // Create labels for the operations

        Vector names = new Vector();
            names.addElement("Brilho");
            names.addElement("Contraste");
        painelBrilhoEContrasteLogico = new GreyMapPanel(imageview,ops,names);
        painelBrilhoEContraste.add(painelBrilhoEContrasteLogico);    
        painelBrilhoEContraste.add(new JScrollPane(imageview));
        registerObserver(observador);
        pack();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBrilhoEContraste = new javax.swing.JPanel();
        botaoAplicar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Brilho e Contraste");
        setName("janelaBrilhoEcontraste"); // NOI18N

        botaoAplicar.setText("Aplicar");
        botaoAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAplicarActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(painelBrilhoEContraste, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(botaoAplicar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelBrilhoEContraste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(198, 198, 198)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAplicar)
                    .addComponent(botaoCancelar))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAplicarActionPerformed
        srcImage = PlanarImage.wrapRenderedImage(imageview.getBufferedImage());
        notifyObserver();
}//GEN-LAST:event_botaoAplicarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    public void registerObserver(JanelaBrilhoEContrasteObserver observador)
    {
        principal = observador;
    }
    
    public void notifyObserver()
    {
        principal.atualizar(srcImage);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAplicar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JPanel painelBrilhoEContraste;
    // End of variables declaration//GEN-END:variables
}
